apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: svc-h1-kubetrain
  replicas: 10
  selector:
    matchLabels:
      tag: label-sts-kubetrain
  template:
    metadata:
      labels:
        tag: label-sts-kubetrain
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
