apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: develop
spec:
  replicas: 2
  selector:
    matchLabels:
      tag: new-httpd
  template:
    metadata:
      labels:
        tag: new-httpd
    spec:
      containers:
      - name: httpd-name
        image: nginx

