apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple
  namespace: develop
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2 

